name: Build and deploy pipeline for tutor service

on:
  push:
    branches:
      - sagnik-dev  # pipeline target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: sagnik-dev  # pipeline target branch to pull

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: jdk
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./backend/Tutor-Service

    - name: Build Docker image
      run: docker build -t Tutor-Service.tar:latest .
      working-directory: ./backend/Tutor-Service

    - name: Save Docker image to file
      run: docker save -o Tutor-Service.tar Tutor-Service.tar:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy Docker image to server
      run: scp -o StrictHostKeyChecking=no Tutor-Service.tar svc-ci@20.224.153.213:/home/svc-ci/deploy

    - name: Copy Docker Compose file to server
      run: scp -o StrictHostKeyChecking=no tutorService/docker-compose.yml svc-ci@20.224.153.213:/home/svc-ci/deploy

    - name: Deploy Docker image on remote server
      run: |
        ssh -o StrictHostKeyChecking=no svc-ci@20.224.153.213 << 'EOF'
        cd /home/svc-ci/deploy
        docker load -i Tutor-Service.tar
        EDULY_DB_URL=${{ secrets.EDULY_DB_URL }} \
        EDULY_DB_USERNAME=${{ secrets.EDULY_DB_USERNAME }} \
        EDULY_DB_PASSWORD=${{ secrets.EDULY_DB_PASSWORD }} \
        docker-compose up -d
        EOF

# svc-edu-tutor username