version: '3.8'

services:
  tutor-service:
    image: tutor-service:latest
    restart: always
    ports:
      - "5001:8080"  # Map host port 5001 to container port 8080
    environment:
      EDULY_DB_URL: ${EDULY_DB_URL}
      EDULY_DB_USERNAME: ${EDULY_DB_USERNAME}
      EDULY_DB_PASSWORD: ${EDULY_DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      BLOB_CONTAINER_NAME: ${BLOB_CONTAINER_NAME}
      BLOB_CONNECTION_STRING: ${BLOB_CONNECTION_STRING}
