name: Build and deploy pipeline for tutor service

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - dev
  workflow_dispatch: # Manual trigger
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and pull request branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: jdk
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -DoutputDirectory=target
        working-directory: ./backend/Tutor-Service
        env:
          EDULY_DB_URL: ${{ secrets.EDULY_DB_URL }}
          EDULY_DB_USERNAME: ${{ secrets.EDULY_DB_USERNAME }}
          EDULY_DB_PASSWORD: ${{ secrets.EDULY_DB_PASSWORD }}
          JWT_SECRET_KEY: '21fb21601b2ba43899bf7dc4f5e942ac946ce936181787992ee68f39f3fa3731'
          BLOB_CONTAINER_NAME: 'demoeduly'
          BLOB_CONNECTION_STRING: 'BlobEndpoint=https://demoeduly.blob.core.windows.net/;QueueEndpoint=https://demoeduly.queue.core.windows.net/;FileEndpoint=https://demoeduly.file.core.windows.net/;TableEndpoint=https://demoeduly.table.core.windows.net/;SharedAccessSignature=sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-09-01T19:22:46Z&st=2024-07-01T11:22:46Z&spr=https,http&sig=4U8%2BOzEB26KyYf3HW9d0FmR5hOetB8qnJ8Q8rdbMmjg%3D'

      - name: Build Docker image
        run: |
          pwd
          ls
          docker build -t tutor-service:latest -f ../Dockerfile .
        working-directory: ./backend/Tutor-Service/target

      - name: Save Docker image to file
        run: docker save -o tutor-service.tar tutor-service:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker image to server
        run: scp -o StrictHostKeyChecking=no tutor-service.tar svc-ci@${{ secrets.SSH_IP }}:/home/svc-ci/deploy

      - name: Copy Docker Compose file to server
        run: |
          pwd
          ls
          scp -o StrictHostKeyChecking=no docker-compose.yaml svc-ci@${{ secrets.SSH_IP }}:/home/svc-ci/deploy
        working-directory: ./backend/Tutor-Service

      - name: Stop and remove existing containers
        run: |
          ssh -o StrictHostKeyChecking=no svc-ci@${{ secrets.SSH_IP }} << 'EOF'
          cd /home/svc-ci/deploy
          docker compose down
          EOF

      - name: Deploy Docker image on remote server
        run: |
          ssh -o StrictHostKeyChecking=no svc-ci@${{ secrets.SSH_IP }} << 'EOF'
          cd /home/svc-ci/deploy
          docker load -i tutor-service.tar
          EDULY_DB_URL=${{ secrets.EDULY_DB_URL }} \
          EDULY_DB_USERNAME=${{ secrets.EDULY_DB_USERNAME }} \
          EDULY_DB_PASSWORD=${{ secrets.EDULY_DB_PASSWORD }} \
          JWT_SECRET_KEY='21fb21601b2ba43899bf7dc4f5e942ac946ce936181787992ee68f39f3fa3731' \
          BLOB_CONTAINER_NAME='demoeduly' \
          BLOB_CONNECTION_STRING='BlobEndpoint=https://demoeduly.blob.core.windows.net/;QueueEndpoint=https://demoeduly.queue.core.windows.net/;FileEndpoint=https://demoeduly.file.core.windows.net/;TableEndpoint=https://demoeduly.table.core.windows.net/;SharedAccessSignature=sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-09-01T19:22:46Z&st=2024-07-01T11:22:46Z&spr=https,http&sig=4U8%2BOzEB26KyYf3HW9d0FmR5hOetB8qnJ8Q8rdbMmjg%3D' \
          docker compose up -d
          echo "$JWT_SECRET_KEY"
          echo "$BLOB_CONTAINER_NAME"
          echo "$BLOB_CONNECTION_STRING"
          echo "$EDULY_DB_USERNAME"
          EOF
        env:
          EDULY_DB_URL: ${{ secrets.EDULY_DB_URL }}
          EDULY_DB_USERNAME: ${{ secrets.EDULY_DB_USERNAME }}
          EDULY_DB_PASSWORD: ${{ secrets.EDULY_DB_PASSWORD }}
          JWT_SECRET_KEY: '21fb21601b2ba43899bf7dc4f5e942ac946ce936181787992ee68f39f3fa3731'
          BLOB_CONTAINER_NAME: 'demoeduly'
          BLOB_CONNECTION_STRING: 'BlobEndpoint=https://demoeduly.blob.core.windows.net/;QueueEndpoint=https://demoeduly.queue.core.windows.net/;FileEndpoint=https://demoeduly.file.core.windows.net/;TableEndpoint=https://demoeduly.table.core.windows.net/;SharedAccessSignature=sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-09-01T19:22:46Z&st=2024-07-01T11:22:46Z&spr=https,http&sig=4U8%2BOzEB26KyYf3HW9d0FmR5hOetB8qnJ8Q8rdbMmjg%3D'
